# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc478104a507f2c1b6fd467f7a4abb2cb0a05d55a5c46ffee32b4be9d66a5b7aa48a71398b6a91275867986d2196305d4337d470779b17aab70419f669eebd20

test:
  secret_key_base: 2ffc2e83f97fea04a31d5fbadf477c173ba5928b759802ff0f318391c6a94f80a46086f7da5905caac72e3168103125eabb0c56a96f4de2d97d1dcab86001f20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
